### ISSUE TITLE
Would like to help

### ISSUE THREAD

**Issue by powershellwhizz** [ThePants999/tts-comp-ftc-base-lua-scripts#2]
Hello ThePants! Not sure how else I could reach out to you so apologies for using "issues" to reach out. I have a few ideas around the FTC map and would like to discuss them further with you. Prob not best putting it all here, do you have a way I can contact you? Your discord name perhaps or email address (if ok putting it here)?

**Comment by ThePants999** [comment]
Rather than put it somewhere bots can scrape it, I'll just say that I'm very easy to find on the TTS40K Discord, https://discord.gg/2ST7xyWgEa - and that might be a good place to converse anyway, since conversations about the map base are good to have in public!

**Comment by powershellwhizz** [comment]
Hi Pants,
I am on there already. Was asking after you 2 days ago but no one responded. My username is BeastMode on there. please reach out so we can have a chat about some ideas and things I am already working on. thanks dude!
