### ISSUE TITLE
Dice rolling buttons sometimes throw errors if pressed while dice are being rolled

### ISSUE THREAD

**Issue by FChippendale** [ThePants999/tts-comp-ftc-base-lua-scripts#21]
If any roll dice buttons are pressed while the dice they reference are in the box, an error is thrown for each dice currently being rolled. This does not disrupt the dice rolling process, however is visually annoying for the host. Becomes more common on low spec PCs, as lag can cause dice to take longer to roll.

Exact error message (Red dice roller in this example, problem also applies to Blue):

`Error in Script (Red Kustom 40k Dice Roller Mk3 - beae28) function <startLuaCoroutine/insidef>: <Unknown Error>`

**Comment by ThePants999** [comment]
Fixed by d05993e19fd4e0624ab80f84f29f06aaac610158
