### ISSUE TITLE
The Investigate Signals button position overlaps during gameplay

### ISSUE THREAD

**Issue by sterling000** [ThePants999/tts-comp-ftc-base-lua-scripts#26]
Hello,

I have seen this issue a few times now, I think it's a minor issue with the new Investigate signals button, it appears to be positioned correctly in the pre-game state of the table, but once the "Start Game" button has been pushed, if you toggle it on and off, the position moves and overlaps the Show Deployment Zones button. See screenshot attached. Repro 100%

 
![image](https://github.com/ThePants999/tts-comp-ftc-base-lua-scripts/assets/8825931/b507df84-1db9-460c-9425-a4a0d60e1e97)

**Comment by ThePants999** [comment]
Forgot I had an issue for this. Fixed now.
