### ISSUE TITLE
Automatic Turn counter randomly stops working

### ISSUE THREAD

**Issue by facelid** [ThePants999/tts-comp-ftc-base-lua-scripts#27]
Almost every game I play, at some point during the game, the turn counter stops working.
Clicking through the Phases or right clicking the button doesn't progress the turns, at which point every counter has to be updated manually.
I haven't been able to find what triggers this issue. 
Some times it's broken from turn one, other times it breaks half way through. It's very rare for it to work through a full game.

The only thing I've noticed is that every time it has broken, one of the players have used fixed missions. And the fixed mission cards don't get flipped over when secondary's are revealed. They are locked face down, and have to be unlocked and manually turned over.

Thanks!

**Comment by ThePants999** [comment]
The face-down-ness is WAD - you're supposed to flip them over yourselves as soon as both players have selected (though I could add some code to automatically flip them as soon as both players have locked them in, I'll likely do that if I get a chance).

Turn counter definitely sounds like a bug, though, thanks! Though it might be tricky for me to find the bug without a repro scenario :(

**Comment by facelid** [comment]
If the fixed cards staying face down isn't a bug, then that's completely fine. It's just a mild inconvenience to have to unlock, flip and lock again. I just found it strange, which is why I assumed it was a bug :)

I'll continue to play around with it and see if I can narrow down the trigger. But so far, the only thing I've noticed is that I've had Fixed missions in all the games where it bugged out. I'm fairly certain that every game where it worked all the way through, both players had tactical missions. My sample size is pretty small though, so it's probably not very useful information.

If there's anything I can do to help you find the bug, please let me know :)

**Comment by facelid** [comment]
Okay.. I'm not happy to admit it, but I'm an absolute idiot.
It's not bugged, it's just locked to prevent the opponent from ending the other players turn. "facepalm"
Since my friend keeps forgetting to use it, I've been trying to help him move the counter along, but it obviously doesn't let me end his turn, so we thought it kept bugging out. But in reality, he just needs to start pressing the button :D
Sorry for wasting your time <3

**Comment by ThePants999** [comment]
Hah, no worries!

Gonna keep the issue open to remind myself to look at auto-flipping the secondaries.

**Comment by ThePants999** [comment]
Fixed in 2aeb85ce7cfac7501cdc873d3d98971ecdd5fc3e
