### ISSUE TITLE
Instruction pdfs are in French

### ISSUE THREAD

**Issue by Heizug** [ThePants999/tts-comp-ftc-base-lua-scripts#29]
The only datasheets/pdfs that are in English are the ones in bags. Almost every pdf that loads onto the table is in French, is there a way to fix that in the options somewhere?

**Comment by ThePants999** [comment]
Well, that's amusing. They're in English for me - I guess there must be some cleverness on the WarCom site that redirects the link to the version in "your" language based on where it understands you to be.

There's a tablet on the table - try navigating to https://www.warhammer-community.com/warhammer-40000-downloads/ on the tablet and changing the download language to English, then reloading the table.

**Comment by Heizug** [comment]
Interesting! I'm having some trouble finding the tablet on the table, is
there a way to search for it?

I was under the impression that since the pdfs are listed as "custom pdf"
when you open them in the scripting editor they were just pics of the
French-language version of the documents.

I suppose it's also possible that these Combat Patrol mods from the Steam
Workshop I'm using are just using your base as an overlay for their own
thing, assuming you're not the listed poster of these mods ("Tera_Pudding"
is the UID in the Workshop).

Just in case it helps/adds clarity, here's a screenshot of what I'm seeing
on the table when the mod loads:

[image: image.png]

**Comment by ThePants999** [comment]
If you're not seeing the tablet, it's likely that whatever you're using has diverged enough from this mod that I'll be unable to help and you'll need to engage the author of the actual mod you're using. Unfortunately, your screenshot didn't upload so I can't confirm, perhaps you could try again via GitHub rather than email?

**Comment by ThePants999** [comment]
Found Tera_Pudding's mods - I don't think they have anything to do with mine at all, I'm afraid.
