### ISSUE TITLE
Targets of opportunity - mission rule

### ISSUE THREAD

**Issue by MrAltF4** [ThePants999/tts-comp-ftc-base-lua-scripts#30]
The Targets of Opportunity - Mission Rule card presents a unique situation in which the table doesn't seem to have a feature that supports this in the clear and semi-automatic manner that it does other cards and mission rules.

Currently we're pulling another secondary from the deck and squeezing this near the other 2 secondaries.

1. Is there a solution for this already and it's not clear to us?
2. Is it worth creating someone bespoke for this one mission card?

Thanks for your time

**Comment by ThePants999** [comment]
You're not missing anything - pulling another from the desk and putting it nearby is indeed the appropriate workaround. I judged that it wasn't worth the effort to do something special for this, especially given that none of the GW recommended tournament missions use that card, and neither do any of the TTS tournaments I've come across.

Naturally, pull requests always welcome if someone else considers it worth their time 😁
