### ISSUE TITLE
Dice roller is not working correctly

### ISSUE THREAD

**Issue by SlicedPumpkin** [ThePants999/tts-comp-ftc-base-lua-scripts#8]
The dice roller places dice at either the wrong value or on one of the edges causing them to roll to the wrong value. I have played with every physics setting in TTS and on the dice. I have uninstalled and reinstalled the mod and that also does not work. See the attached for a video of what I mean.
[Incorrect Dice Roller.zip](https://github.com/ThePants999/tts-comp-ftc-base-lua-scripts/files/9770035/Incorrect.Dice.Roller.zip)

**Comment by ThePants999** [comment]
This might be fixed in the latest version. I'd be grateful if you could let me know if it is.

**Comment by SlicedPumpkin** [comment]
Hey ThePants999,

I checked and it now seems to be working normally. Thank you for the fix
much appreciated.

**Comment by ThePants999** [comment]
Awesome.
